# Generated by Django 5.0.4 on 2024-05-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_type',
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dishes.dish')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dishes.dishestype')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_types',
            field=models.ManyToManyField(through='dishes.DishType', to='dishes.dishestype'),
        ),
    ]
