# Generated by Django 5.0.4 on 2024-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_dish_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_published',
            field=models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовано')], default='DF', max_length=2),
        ),
    ]
