# Generated by Django 5.0.4 on 2024-05-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_acidcompositioninformations_alanin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='alanin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='arginine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='aspartic_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='cysteine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='glutamic_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='glycine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='histidine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='isoleucine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='leucine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='lysine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='methionine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='omega3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='phenylalanine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='proline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='serin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='threonine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='tryptophan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='tyrosine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acidcompositioninformations',
            name='valin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesinformations',
            name='glycemic_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesinformations',
            name='insulin_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='ca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='cl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='cr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='cu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='fe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='i',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='mg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='mn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='mo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='na',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='si',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microelementsinformations',
            name='zn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='products.ProductToCategory', to='products.productscategory'),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='proteins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='starch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='trans_fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmaininformation',
            name='water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='alpha_carotene',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='beta_carotene',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='coenzyme_q10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b11',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b13',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_b9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitaminsinformations',
            name='vitamin_u',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
