# Generated by Django 5.0.4 on 2024-05-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_acidcompositioninformations_alanin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producttocategory',
            unique_together={('product', 'category')},
        ),
    ]
